vocabulary = {
    "diabetes mellitus": "Diabetes",
    "resistencia a insulina": "Diabetes",
    "hiperglicemia": "Diabetes",
    "diabetes tipo 1": "Diabetes",
    "diabetes tipo 2": "Diabetes",
    "dm1": "Diabetes",
    "dm2": "Diabetes",
    "diabetes": "Diabetes",
    "sobrepeso": "Obesidade",
    "obesidade mórbida": "Obesidade",
    "imc elevado": "Obesidade",
    "indice de massa corporal elevado": "Obesidade",
    "dislipidemia": "Dislipidemia",
    "hiperlipidemia": "Dislipidemia",
    "alteraçoes do lipidograma": "Dislipidemia",
    "colesterol alto": "Dislipidemia",
    "ldl elevado": "Dislipidemia",
    "hdl baixo": "Dislipidemia",
    "dlp": "Dislipidemia",
    "triglicerideos elevados": "Dislipidemia",
    "tabagismo": "Tabagismo",
    "fumante": "Tabagismo",
    "uso de tabaco": "Tabagismo",
    "dependencia de nicotina": "Tabagismo",
    "hipertensao": "Hipertensão",
    "has": "Hipertensão",
    "pressão alta": "Hipertensão"
}
